# Omit dependency build caching for release build.
# Because we need clean build everty time for release build.
FROM rust:1.80-bookworm as builder

WORKDIR /usr/src/

COPY . .

RUN --mount=type=cache,target=/usr/local/cargo/registry \
  --mount=type=cache,target=/usr/src/app/target \
  cargo install --path .

FROM ubuntu:24.04
COPY --from=builder /usr/local/cargo/bin/orgu /usr/local/bin/orgu

ENTRYPOINT ["/usr/local/bin/orgu"]
CMD ["front", "lambda"]
