# Omit dependency build caching for release build.
# Because we need clean build everty time for release build.
FROM rust:1.85-alpine AS builder

RUN apk add --update-cache musl-dev pkgconfig libressl-dev

WORKDIR /usr/src/app/

COPY . .

RUN --mount=type=cache,target=/usr/local/cargo/registry \
  --mount=type=cache,target=/usr/src/app/target \
  cargo install --path .

FROM alpine:3.21
COPY --from=builder /usr/local/cargo/bin/orgu /usr/local/bin/orgu

ENTRYPOINT ["/usr/local/bin/orgu"]
CMD ["front", "lambda"]
