name: clippy-action
on: [pull_request]
jobs:
  clippy:
    runs-on: ubuntu-latest-16core
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # Latest as of 2023-11-16
      with:
        toolchain: stable
        components: clippy
    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
    - uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
      with:
        reporter: 'github-pr-check'
        github_token: ${{ secrets.GITHUB_TOKEN }}
